# Generated by Django 3.1 on 2020-10-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='max_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='min_price',
            field=models.IntegerField(),
        ),
    ]
